/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.glb --transofm 
*/
"use client"

import { useTrailer } from '@/hooks/useTrailer';


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Trailer(props) {
  const { nodes, materials } = useGLTF('/model/Green.glb');

  const {
    oversides,
    rear,
    bavero,
    motor,
    cover,
    suspensions,
    wheel,
    secondStandFoot,
  } = useTrailer();





  return (
    <group {...props} dispose={null} castShadow receiveShadow>
      <group position={[0.128, 0.165, -0.858]} scale={0.218}>
        {/* Parte Sotto */}
        <group position={[-0.587, -3.061, 9.49]}>
          <mesh geometry={nodes.Plane016.geometry} material={materials.Lower_Body} />
          <mesh geometry={nodes.Plane016_1.geometry} material={materials['Lower_Body.002']} />
          <mesh geometry={nodes.Plane016_2.geometry} material={materials['Lower_Body.003']} />
        </group>
        
        <group position={[1.788, 0.609, 8.588]} rotation={[-0.173, 0, -Math.PI / 2]}>
          {/* <mesh geometry={nodes.Cylinder011.geometry} material={materials.Oversized_Tailgate} /> */}
          
          {/* Retro normale */}
          {rear === "Normal" && (
            <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.Normal_Tailgate} />
          )}
        </group>

        {/* Cover 2 */}
        {cover === "Cover_2" && (
          <mesh 
            geometry={nodes.Cover2.geometry} 
            material={materials.Cover_2} 
            position={[-1.793, -0.779, 5.077]} 
            rotation={[0, 0.002, 0]}
            scale={[1, 
              oversides === "No" ? 0.95 : 1.2  
              , 1]}
          />
        )}

        {/* Cover 1 */}
        {cover === "Cover_1" && (
          <>
            <mesh 
              geometry={nodes.Cover1.geometry} 
              material={materials.Cover_01} 
              position={[-0.082,
                oversides === "No" ? -0.9 : -0.134
                , 1.153]} 
            />
            <mesh 
              geometry={nodes.cover1_2.geometry} 
              material={materials.Cover_01} 
              position={[-0.082, 
                oversides === "No" ? 1.7 : 2.502
                , -2.203]} 
              rotation={[-2.156, 0, 0]} 
            />
          </>
        )}

        {/* Oversides 1 Oversized */}
        {oversides === "50cm" && rear == "Oversized" && (
          <>
            <mesh geometry={nodes.Oversides_1_Rear_Oversized_1.geometry} material={materials['Oversides_01.001']} position={[-0.64, 2.01, 0.442]} />
            <mesh geometry={nodes.Oversides_1_Rear_Oversized_2.geometry} material={materials['Oversides_01.001']} position={[-0.082, -0.187, 0.286]} scale={[1, 1, 1.206]} />
            <mesh geometry={nodes.Oversides_1_Rear_Oversized_3.geometry} material={materials['Oversides_01.001']} position={[-0.082, -0.187, 1.153]} scale={[1, 1, 1.069]} />
          </>
        )}

        {/* Oversides 1 Normal */}
        {oversides === "50cm" && rear === "Normal" && (
          <>
            <mesh geometry={nodes.Oversides_1_Rear_Normal_1.geometry} material={materials.Oversides_01} position={[-0.64, 2.01, 0.442]} />
            <mesh geometry={nodes.Oversides_1_Rear_Normal_2.geometry} material={materials.Oversides_01} position={[-0.082, -0.187, 1.153]} />
            <mesh geometry={nodes.Oversides_1_Rear_Normal_3.geometry} material={materials.Oversides_01} position={[-0.082, -0.187, 1.153]} />
          </>
        )}

        {/* Ruote Oversized */}
        {wheel === "Oversized" && (
          <>
            <mesh geometry={nodes.Tyre_Oversized_Centre.geometry} material={materials.Large_Wheels} position={[1.417, -3.377, 8.007]} scale={[3.96, 3.853, 3.853]} />
            <mesh geometry={nodes.Tyre_Oversized_Leather002.geometry} material={materials.Large_Wheels} position={[1.514, -3.377, 8.007]} rotation={[-0.157, 0, 0]} scale={[0.76, 1, 1]} />
          </>
        )}

        {/* Ruote Normali */}
        {wheel === "Normal" && (
          <>
            <mesh geometry={nodes.Tyre_Normal_Centre.geometry} material={materials.Small_Wheel_Black} position={[1.258, -3.377, 8.007]} />
            <mesh geometry={nodes.Tyre_Normal_Leather.geometry} material={materials.Large_Wheels} position={[1.514, -3.377, 8.007]} rotation={[-0.157, 0, 0]} scale={[0.76, 1, 1]} />
          </>
        )}

        {/* Body */}
        <mesh geometry={nodes.Body_Normal.geometry} material={materials.Main_Body} position={[-0.082, -0.187, 1.153]} />

        {/* Oversides 2 Oversized */}
        {oversides === "50+35cm" && rear === "Oversized" && (
          <>
            <mesh geometry={nodes.Oversides_2_Rear_Oversized_1.geometry} material={materials['Oversides02.001']} position={[-0.64, 2.009, 0.442]} />
            <mesh geometry={nodes.Oversides_2_Rear_Oversized_2.geometry} material={materials['Oversides02.001']} position={[-0.082, -0.181, 1.103]} scale={[1, 1, 1.02]} />
            <mesh geometry={nodes.Oversides_2_Rear_Oversized_3.geometry} material={materials['Oversides02.001']} position={[-0.082, -0.181, 0.077]} scale={[1, 1, 1.171]} />
          </>
        )}

        {/* Oversides 2 Normal */}
        {oversides === "50+35cm" && rear === "Normal" && (
          <>
            <mesh geometry={nodes.Oversides_2_Rear_Normal_1.geometry} material={materials.Oversides02} position={[-0.64, 2.009, 0.442]} />
            <mesh geometry={nodes.Oversides_2_Rear_Normal_2.geometry} material={materials.Oversides02} position={[-0.082, -0.181, 1.153]} />
            <mesh geometry={nodes.Oversides_2_Rear_Normal_3.geometry} material={materials.Oversides02} position={[-0.082, -0.181, 1.153]} />
          </>
        )}

        {/* Suspensions */}
        {suspensions === "Si" && (
          <>
            <mesh geometry={nodes.Syspension.geometry} material={materials.Suspension} position={[-0.587, -3.061, 9.49]} />
            <mesh geometry={nodes.Suspension_Holder.geometry} material={materials.Suspension} position={[-0.587, -3.061, 9.49]} />
          </>
        )}
        

        {/* Second Foot */}
        {secondStandFoot === "Si" && (
          <mesh geometry={nodes.Seconf_Stand_Foot.geometry} material={materials['Side Support']} position={[-0.587, -3.061, 9.49]} />
        )}

        {/* Motor 2 */}
        {motor === "Motor_2" && (
          <mesh geometry={nodes.Motor_2.geometry} material={materials.Lower_Body} position={[-0.587, -3.143, 9.49]} />
        )}

        {/* Motor 1 */}
        {motor === "Motor_1" && (
          <mesh geometry={nodes.Motor_01.geometry} material={materials.Lower_Body} position={[-1.08, -2.39, 0.049]} rotation={[Math.PI / 2, 0, 0]} />
        )}


        {/* Portellone Maggiorato */}
        {rear === "Oversized" && (
          <mesh geometry={nodes.Rear_Tailgate_Oversized.geometry} material={materials.Oversized_Tailgate} position={[0.05, 1.237, 6.113]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 1.346]} />
        )}

        {/* Bavero Oversized */}
        {bavero === "Si" && rear === "Oversized" && (
          <mesh geometry={nodes.Bravo_Overside_01.geometry} material={materials.Oversized_Tailgate} position={[0.05, 1.237, 6.113]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 1.346]} />
        )}

        {/* Bavero Normale */}
        {bavero === "Si" && rear === "Normal" && (
          <mesh geometry={nodes.Normal_Overside.geometry} material={materials.Normal_Tailgate} position={[1.788, 0.609, 8.588]} rotation={[-0.173, 0, -Math.PI / 2]} />
        )}
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
